[profile.v0_8]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@dragonswap/v2-periphery/contracts/=lib/v2-periphery/contracts/',
    '@dragonswap/v2-core/contracts/=lib/v2-core/contracts/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
